In [1]:
import torch

In [2]:
# 'arange' is used to get a range of values e.g (0 to 10(exclusive))
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and view - We use the 'reshape' func to shape the tensors to rows and columns
my_torch = my_torch.reshape(2, 5) # The rows and columns must fit the size
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
#Reshape if you don't know the number of items
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
# the rows must be able to divide the range size as well, like 10 / 2 works, so we can use it
my_torch2 = my_torch2.reshape(-1, 5) # The '-1' is for something we don't know, like the column/row
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [12]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#View and reshape are very similar, but also have their differences
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
#With reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [30]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [31]:
my_torch6 # It changes to the updated value of my_torch5

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [32]:
#SLICES
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# This is not the number 7, but the scalar value of 7
#Grab a specific item
my_torch7[7]

tensor(7)

In [35]:
#Grab a slice
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [38]:
#Grabbing the Numbers: '1, 3, 5, 9'
my_torch8[:, 1] # the comma ',' is needed, remeber

tensor([1, 3, 5, 7, 9])

In [39]:
#What if we want to keep the shape and return the column?
my_torch8[:, 1: ]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])