In [1]:
pip install torch torchaudio torchvision

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
import numpy as np

# NUMPY Revision

In [3]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
a[1, 2]

8

In [5]:
a.itemsize # This represents sizes of each elements to be 4 bytes

4

In [6]:
a.shape # This shows the number of rows and columns that we have

(2, 5)

In [8]:
a[:, 3] = 8 # This  is used to edit a particular column, the ':' is used to  pick the whole row
print(a)

[[ 1  2  3  8  5]
 [ 6  7  8  8 10]]


In [13]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # This is a 3-dimensional array
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a[0, 1, 0] 
# The '0' is used to get the first row, and the '1' is used to get the 
# second row in the first 3d, and the '0' is used to get the first index in
# that row

3

In [16]:
#ALl 0's Matrix
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((2, 3, 4)) 
# ((how many rows, how many columns per row, how many columns in total))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
np.full((4, 2), 666) #((r, c), values)

array([[666, 666],
       [666, 666],
       [666, 666],
       [666, 666]])

In [21]:
a  = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [27]:
# Addition
b = a + 2
b

array([3, 4, 5, 6, 7])

In [24]:
a // 2

array([0, 1, 1, 2, 2], dtype=int32)

In [25]:
a - 1

array([0, 1, 2, 3, 4])

In [28]:
b * 2

array([ 6,  8, 10, 12, 14])

In [29]:
np.random.rand(3, 2)

array([[0.00828874, 0.76414477],
       [0.9386838 , 0.87423923],
       [0.65003378, 0.30380247]])

In [30]:
np.random.rand(3, 2, 5) # (3 rows, 2 rows per each row, 5 columns)

array([[[0.46636919, 0.50205098, 0.62342603, 0.96982021, 0.17314073],
        [0.8054262 , 0.96845928, 0.81586989, 0.83705499, 0.21963332]],

       [[0.32715869, 0.37361648, 0.20968064, 0.71197275, 0.32042085],
        [0.34229174, 0.95385178, 0.26371072, 0.70832108, 0.13692188]],

       [[0.15652842, 0.0759166 , 0.3538984 , 0.05747106, 0.35672736],
        [0.875227  , 0.4327272 , 0.37229544, 0.32339768, 0.73644308]]])

In [36]:
#Creation of integer values
np.random.randint(2, 10, size= (4, 4))
#(a,  b, size=(r, c)), the lowest possible value is going to be 'a'(inclusive), and the highest possible value is going to be 'b'(exclusive)
# the 'a' and 'b' are ranges

array([[4, 5, 9, 6],
       [5, 9, 2, 2],
       [9, 9, 3, 6],
       [5, 6, 2, 8]])

In [37]:
np.random.choice(['me', 'you'], size= (3, 2))

array([['me', 'you'],
       ['me', 'you'],
       ['me', 'me']], dtype='<U3')

In [43]:
np1 = np.random.rand(3, 4)
np1

array([[0.4953225 , 0.23022054, 0.62277061, 0.35659806],
       [0.97804376, 0.44631588, 0.37695991, 0.9949988 ],
       [0.48538035, 0.75199755, 0.72464748, 0.07133965]])

# Tensors

In [39]:
# Tensors are very similar to arrays but specifically created for Deep Learning
tensor_2d = torch.randn(3, 4) # This is tensors using the torch library
tensor_2d

tensor([[-0.2855,  0.5648, -0.4885, -0.5913],
        [-0.8088,  1.3789,  0.3901,  0.3774],
        [ 1.4651, -1.1554,  0.4124, -0.0106]])

In [46]:
tensor_3d = torch.zeros(2, 3, 4) # (2 rows, 3 rows per each 3d row, 4 columns in total)
tensor_3d
tensor_3d.dtype

torch.float32

In [45]:
# Create tensor out of numpy array 
my_tensor = torch.tensor(np1) # tensor being created out of numpy
my_tensor

tensor([[0.4953, 0.2302, 0.6228, 0.3566],
        [0.9780, 0.4463, 0.3770, 0.9950],
        [0.4854, 0.7520, 0.7246, 0.0713]], dtype=torch.float64)

# Tensors operations