# Tensor Math 

In [1]:
import torch

In [5]:
#Whenever you use a built in function, the list must be square brackets '[]'
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [6]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
# Addition long hand
torch.add(tensor_a, tensor_b) # Does the same thing but just a built in func

tensor([ 6,  8, 10, 12])

In [8]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [10]:
# Sub funcf
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [11]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
#Mul long hand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
#Division
tensor_b / tensor_a # Turns it into a float

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Div long hand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
#Remainder
tensor_b % tensor_a # Using the modulus

tensor([0, 0, 1, 0])

In [16]:
# Remainder long hand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [17]:
# Exponents - Raised to power
tensor_a**tensor_b

tensor([    1,    64,  2187, 65536])

In [18]:
# Exponents long div
torch.pow(tensor_a, tensor_b) # Yes, its actually pow :)

tensor([    1,    64,  2187, 65536])

In [19]:
# Easier way to write long hand, using the built in function with 'period(.)'
tensor_a.add(tensor_b) # Same thing can be done to the rest!

tensor([ 6,  8, 10, 12])

In [20]:
#Re-assignment using underscore: '_'
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a

tensor([1, 2, 3, 4])

In [24]:
# tensor_a = tensor_a + tensor_b OR use '_'
tensor_a.add_(tensor_b) # the underscore reassigns the value of the answer to 'tensor_a'

tensor([ 6,  8, 10, 12])

In [25]:
tensor_a # See it here.

tensor([ 6,  8, 10, 12])

In [26]:
torch.add_(tensor_a, tensor_b) # this is WRONG, the '_' works only with the variable name

AttributeError: module 'torch' has no attribute 'add_'