## The Basics of Numpy

In [1]:
import numpy as np


# Ensure you have numpy installed before running the above code
# Note: numpy can be imported as anything, the 'np' is just a conventional method
# We are importing numpy as 'np' here so we can use it to turn raw values to arrays

In [2]:
a = np.array([1, 2, 3]) 
print(a)

# This is a 1d array and how you can initialize the array by setting 'np.array([values])'

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]]) 
print(b)


# This is a 2 dimensional array, each square bracket[] seperated by a comma ',' 
# Note: arrays can only be of one data type, if they are going to be floats(2.0) make them floats...
# Note: ...if they are going to be integers(3) make the whole array integers, 
# Note: Mixing them up would result in an error e.g(1, 3.0, 5, 7.1) is WRONG

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
a.ndim

# This tells us the dimension of an array, which we've already specified....
# that 'a' was a 1 dimensional array

1

In [5]:
b.ndim 

# (n) means number of,  (dim) means dimensional arrays

2

In [6]:
a.shape

# Get shape, This tells us the amount of rows and columns in an array
# which, in this case, 'a' is only 3 columns

(3,)

In [7]:
b.shape 

# This tells us we have 2 rows and 3 columns

(2, 3)

In [8]:
a.dtype

# Get type this tells us the type of data it is, best to specify the dtype to save space

dtype('int32')

In [9]:
a.itemsize

# To get size

4

In [10]:
b.itemsize

# Float sizes are bigger than integers

8

In [11]:
a.size

# To get total values

3

In [12]:
a.nbytes

#To get  total size is: 'nbytes'

12

Accessing/Changing specific elements in rows,columns,etc

In [13]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

# This is a 2 by 7 array, meaning 2 rows and 7 columns each

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
a.shape

(2, 7)

In [15]:
a[1, -2] or a[1, 5]

# Getting a specific element using [r, c]
# You can use both posiive and negative indexing

13

In [16]:
a[0, : ]

# Getting a specific row
# We use slice just like in lists

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
a[:, 2]

# Getting a specific column
# This ':,' will get all the rows and then you specify the column

array([ 3, 10])

In [18]:
a[0, 1: 6:2]

# Getting a little more fancy [startindex:endindex:stepsize]
# The '0' will get me the first row, the '1:' is to start from the second element

# The '6:' will get me all elements up to the 6th index, excluding the 6th index
# Which means it will be getting me from 1,which is '2' to 6, which is '6'

#the ':2' is a "STEP" just like in lists to print "2,4,6" of the first row(even numbers)

array([2, 4, 6])

In [19]:
a[1, 0:6 :2]

# This takes the second row, then initialize the index start and end
# then initialize the 'Step'

array([ 8, 10, 12])

In [20]:
a[1, 5] = 20
print(a)

# Changing values in an array, first initialize the row, and column
# This shows the value of '13' has been changed to '20'

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
a[:, 2] = 5
a

# Instead of using 'print(a)' we call 'a' because jupyter notebook allows that for easier usability
# Changing series of values in an array
# This shows the values of that 'Column' has changed

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [22]:
a[:, 2] = [1,2]
a

# This will specify and change the values of the column

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [23]:
a[1:, 4] = 99
a

# similar example

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 99, 20, 14]])

In [24]:
a.size

14

In [25]:
a.itemsize

4

In [26]:
a.nbytes

56

In [27]:
a.shape

(2, 7)