In [1]:
import numpy as np

3d Examples

In [12]:
# using this amount of square brackets '[[]]'...
# and then splitting the arrays

b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [14]:
print(b)


# in the 'print' function you can see that we have 2 distinct rows...

# let's call this: ([1, 2], 
#                  [3, 4])  ROW 1


# let's call this: ([5, 6]
#                  [7, 8]) ROW 2

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
b.shape


# This is used to get the shape of the array...
# ...in which in this case is (2, 2, 2)....
# which means (2 distinct rows, 2 rows in eaach "total first & second" rows, 2 columns in all rows )

(2, 2, 2)

In [17]:
b[0,1, 1]

#Get specific element(work outside in)
# The '0' is to pick ROW 1, the '1' is to pick the 2nd row in ROW 1
#The other '1' is to pick the value in the 2nd row [3, '4']

4

In [18]:
b[1, 0, 0]

# this time we are getting the ROW 2, then the first row in the ROW 2
# ....then the first value of that row(following 'indexing' rule in python)

5

In [19]:
# This [:] shows that i want to pick ROW 1 & ROW 2...
# ... then the second [1] row of the two ROWS, ([3,4]) and (7, 8)
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [20]:
b[:, 1, :] = [[9,9], [8,8]]

# Replacing the values of the array...
# ensuring the new values we are setting matches the rows/columns we are picking 
# in this case we are picking the rows from the above cell and....
# replacing their values with "[[9,9], [8,8]]"

In [22]:
b

# Now if we call the array 'b' you will notice...
# that the values of the second rows in ROW 1 & 2 have changed

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Modify the array has much as you want to fully understand it before moving to the next notebook...