In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]]) 

In [3]:
np.zeros((2, 2))

#All 0's Matrix
# Using the built in function '.zeros'

array([[0., 0.],
       [0., 0.]])

In [4]:
np.ones((4, 2, 2))

# All one's matrix
# ((rows, how_many_columns_per_row , how_many_columns_in_total))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [5]:
np.ones((6, 2, 3))

# Specifying the ROWS, rows per each ROW and columns 

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
np.full((2,2), 99) 

# Any other number Matrix- Specify the value wanted
#((row, column), values)

array([[99, 99],
       [99, 99]])

In [7]:
np.full((3, 2),  77, dtype = 'float64')

# You can as well specify the data type

array([[77., 77.],
       [77., 77.],
       [77., 77.]])

In [8]:
np.full(a.shape, 44) 

# Any other number (full) while trying to use the shape of another array
# (arary_Shape_we_are_using, the value we want to pass in)

array([44, 44, 44])

In [9]:
np.full(a.shape, 55)
# OR
np.full_like(a, 6)

# This 2 would give the same result

array([6, 6, 6])

In [10]:
np.random.rand(4, 2, 3)

# Using the 'random' method
# Initializing an array of random decimal numbers

array([[[0.15161218, 0.23220142, 0.90393372],
        [0.73957311, 0.01508375, 0.59033785]],

       [[0.14287141, 0.69471146, 0.36082567],
        [0.38691617, 0.83437049, 0.09274924]],

       [[0.56456939, 0.86828259, 0.02418361],
        [0.01399229, 0.22665058, 0.02349943]],

       [[0.78437729, 0.01586011, 0.94611866],
        [0.64436719, 0.03248195, 0.18459602]]])

In [11]:
np.random.randint(2, 8, size = (3,3))

# Initializing an array of Integer values
# (all numbers except for the number written, and the size of the (r, c))

array([[3, 3, 3],
       [5, 5, 2],
       [4, 7, 6]])

In [12]:
np.identity(3)

# Creating an identity matrix
# This only needs one parameter

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

# Repeating an array
# To make it print in format '1,2,3- 1,2,3' we will use the axis method

[1 1 1 2 2 2 3 3 3]


In [14]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

# if we also need to make it a 2 dimensional array

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [15]:
output = np.ones((5, 5))
print(output)

# Assigning an identity matrix to a variable

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

# Assigning an identity matrix to a variable
# While assigning the value at [1, 1] to be equal to 9

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [17]:
output[1:4, 1:4] = z 
print(output)

# Picking particular rows and columns and assigning them to variable 'z'
# output[specify the rows, which is from 1 to 4 excluding 4th row, same thing with column]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays

In [18]:
a = np.array([1, 2, 3])
b == a

# You shouldn't assign them to the same memory storage e.g 'b = a', instead let them have the same values 'b == a'

array([[False, False, False],
       [False, False, False]])

In [19]:
b[0] = 100
b

array([[100., 100., 100.],
       [  6.,   5.,   4.]])

In [20]:
b = a.copy() # This copies the contents of a
b[1] = 65   # 'b' has the same values as 'a' using the '.copy()' method, here we are changing the value at the index[1] to '65'
print(b)
print(a)

[ 1 65  3]
[1 2 3]


### Modify the array as much as you can before you move to the next notebook