In [1]:
import numpy as np

## Addition(+)
## Subtraction(-)
## Division (/)
## Multiplication (*)
## Power (**)
## sine(sin)
## cosine(cos)

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
a + 2 

# Adds 2 to each element

array([3, 4, 5, 6])

In [4]:
a - 2

# Subtracts 2 from each element

array([-1,  0,  1,  2])

In [5]:
a * 2

# Multiply each elements by 2

array([2, 4, 6, 8])

In [6]:
a/2

# divide each elements by 2

array([0.5, 1. , 1.5, 2. ])

In [7]:
a += 2
a

# This is going to give the same values as 'a + 2'...
# just that it will save it to var 'a' unlike the previous one which does...
# ...only the calculations and not save inplace

array([3, 4, 5, 6])

In [8]:
b = np.array([1, 0, 1, 0])
a + b

# adds each values of a[3, 4, 5, 6] to each values of 'b'
# we are talking 
# ...[1+3, 0+4, 1+5, 0+6]

array([4, 4, 6, 6])

In [9]:
a ** 2

# The power calculation i.e a raised to the power of 2...
# ...each values of a[3, 4, 5, 6] raised to the power of 2

array([ 9, 16, 25, 36], dtype=int32)

In [10]:
np.sin(a)

# Take sine of all values :)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [11]:
np.cos(a)

# Take the cos, sin, and even tan

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])