# Linear Algebra

In [1]:
import numpy as np

In [2]:
a = np.ones((2, 3)) # (row, column)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
b = np.full((3,2), 2) # ((row, column), value)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [4]:
# In matrices you have to have the rows be equivalent to the column of the other matrix
np.matmul(a, b) # This is a matrix built in func, normal 'a *b' wouldn't work

array([[6., 6.],
       [6., 6.]])

In [5]:
# Finding the determinant of a matrix
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
np.linalg.det(c) # np is the name of the numpy imported, linalg == linear algebra, det == determinat

1.0

## Statistics in Numpy/Matrices

In [7]:
stats = np.array([[1,2,3], [4, 5,6 ]]) # 2 dimensional array
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# This gets the min value of stats
np.min(stats, axis = 1) # this will give the minimum of the first and second row

array([1, 4])

In [9]:
# This gets maximum value of stats
# The biggest values in the 2 rows. '3' in first ROW,6 in the second row 
np.max(stats, axis = 1)

array([3, 6])

In [10]:
np.sum(stats)# This is going to sum all the elements in the array/matrix
np.sum(stats, axis = 0) # This will add up all the terms going downwards
# [1+4, 2+5, 3+6] adding first row with second row per column

array([5, 7, 9])

## Reorganizing Arrays

In [11]:
# Changing the shape of an array
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [12]:
#re-assigning the values of the array to a new variable
after = before.reshape((8, 1)) # The reshape method uses double brackets '((r, c))'
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [13]:
#  Vertically stacking Matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [14]:
np.vstack([v1, v2]) # This is me stacking an array on top of another one
np.vstack([v1, v2, v1, v2]) # This will even give me multiple copies of the array
# vstack is the built in function use to run the stacking - STACKS in Linear Data Structures.

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# Horizontal stacks
h1 = np.ones((2, 4))
h2 = np.zeros((2,2))

In [16]:
print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [17]:
np.hstack((h1, h2)) # This is horizontally stacking

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])