# Working with Numpy

In [1]:
import numpy as np

The Basics

In [2]:
a = np.array([1, 2, 3]) # This is a 1d array
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]]) #This is a 2 dimensional array
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# This tells us the dimension of an array
a.ndim

1

In [5]:
b.ndim # This means (n) number of (dim) dimensional arrays

2

In [6]:
# Get shape, This tells us the amount of rows and columns in an array
a.shape

(3,)

In [7]:
b.shape # This tells us we have 2 rows and 3 columns

(2, 3)

In [8]:
# Get type this tells us the type of data it is, best to specify the dtype to save space
a.dtype

dtype('int32')

In [9]:
# To get size 
a.itemsize

4

In [10]:
#Float sizes are bigger than integers
b.itemsize

8

In [11]:
# To get total values
a.size

3

In [12]:
#To get  total size is:
a.nbytes

12

Accessing/Changing specific elements in rows,columns,etc

In [13]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]]) # This is a 2 by 7 array
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
a.shape

(2, 7)

In [15]:
#Getting a specific element using [r, c]
a[1, -2] or a[1, 5] # You can use both posiive and negative indexing

13

In [16]:
# Getting a specific row
a[0, : ] # We use slice just like in lists

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Getting a specific column
a[:, 2]# This ':,' will get all the rows and then you specify the column

array([ 3, 10])

In [18]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1: 6:2] # The '0' will get me the first row, the '1:' is to start from the second elemnt
# The '6:' will get me all elements up to the 6th index, excluding the 6th index
# Which means it will be getting me from 1,which is '2' to 6, which is '6'
#the ':2' is a "STEP" just like in lists to pring "2,4,6" of the first row

array([2, 4, 6])

In [19]:
a[1, 0:6 :2] # This takes the second row, then initialize the index start and end
# then initialize the 'Step'

array([ 8, 10, 12])

In [20]:
# Changing values in an array, first initialize the row, and column
a[1, 5] = 20
print(a) # This shows the value of '13' has been changed to '20'

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
#Changing series of values in an array
a[:, 2] = 5
print(a) # This shows the values of that 'Column' has changed

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [22]:
a[:, 2] = [1,2]
print(a) # This will specify and change the values of the column

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [23]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [24]:
a[1:, 4] = 99
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 99 20 14]]


In [25]:
a.size

14

In [26]:
a.itemsize

4

In [27]:
a.nbytes

56

In [28]:
a.shape

(2, 7)

3d Example

In [29]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])# It seems 3d arrays are always
# using '[[]]' this amount of square brackets
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
b.shape

(2, 2, 2)

In [31]:
#Get specific element(work outside in)
b[0,1, 1] # The '0' is to pick the first 2 rows, the '1' is to pick the 2nd row
#The other '1' is to pick the value in the 2nd row

4

In [32]:
b[1, 0, 0]

5

In [33]:
b[:, 1, :] # This shows that i want to print the second row of the 2 distinct rows

array([[3, 4],
       [7, 8]])

In [34]:
# Replacing the values of the array
b[:, 1, :] = [[9,9], [8,8]]


Initializing Differrent Types of Arrays

In [35]:
#All 0's Matrix
np.zeros((2, 2)) # Using the built in function '.zeros'

array([[0., 0.],
       [0., 0.]])

In [36]:
#All one's matrix
np.ones((4, 2, 2)) # ((rows, how_many_columns_per_row , how_many_columns_in_total))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [37]:
np.ones((6, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
# Any other number Matrix
np.full((2,2), 99) #((row, column), values)
# You can as well specify the data type
np.full((3, 2),  77, dtype = 'float64')

array([[77., 77.],
       [77., 77.],
       [77., 77.]])

In [39]:
#Any other number (full) while trying to use the shape of anothe array
np.full(a.shape, 44) # (arary_Shape_we_are_using, the value we want to pass in)

array([[44, 44, 44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44, 44, 44]])

In [40]:
np.full(a.shape, 55)
# OR
np.full_like(a, 6)

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [41]:
# Initializing an array of random decimal numbers
np.random.rand(4, 2, 3)

array([[[3.74961577e-01, 6.11403449e-01, 9.64393434e-01],
        [9.95803846e-01, 2.89747997e-01, 4.60617046e-01]],

       [[3.80111980e-01, 4.57765154e-01, 3.25824211e-02],
        [5.16957846e-01, 7.64443221e-01, 9.24930087e-01]],

       [[6.71380005e-01, 3.98856037e-02, 3.02270707e-01],
        [2.12732379e-01, 3.10500264e-01, 1.15737472e-01]],

       [[5.15976801e-04, 9.04974034e-01, 7.21206036e-01],
        [4.78560950e-01, 1.75438999e-01, 1.44811695e-01]]])

In [42]:
# Initializing an array of Integer values
np.random.randint(2, 8, size = (3,3)) # (all numbers except for the number written, and the size of the (r, c))


array([[2, 3, 4],
       [6, 4, 2],
       [7, 5, 3]])

In [43]:
# Creating an identity matrix
np.identity(3) # This only needs one parameter

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Repeating an array
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)
# To make it print in format '1,2,3- 1,2,3' we will use the axis method
arr = np.array([[1,2,3]]) # we also need to make it a 2 dimensional array
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [45]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4, 1:4] = z # output[specify the rows, which is from 1 to 4 excluding 4th row, same thing with column]
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays

In [46]:
a = np.array([1, 2, 3])
b == a # you shouldn't assign them to the same memory storage e.g 'b = a', instead let them have the same values 'b ==a'
b[0] = 100
b
print(a)

# OR

b = a.copy() # This copies the contents of a
b[1] = 65
print(b)
print(a)

[1 2 3]
[ 1 65  3]
[1 2 3]


C:\Users\YK Gaji\AppData\Local\Temp\ipykernel_7808\1759853172.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  b == a # you shouldn't assign them to the same memory storage e.g 'b = a', instead let them have the same values 'b ==a'


#  Mathematics using Numpy

In [47]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [48]:
a + 2 # Adds 2 to each element


array([3, 4, 5, 6])

In [49]:
a - 2 # Subtracts 2 from each element

array([-1,  0,  1,  2])

In [50]:
a * 2

array([2, 4, 6, 8])

In [51]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [52]:
a += 2
a

array([3, 4, 5, 6])

In [53]:
b = np.array([1, 0, 1, 0])
a + b

array([4, 4, 6, 6])

In [54]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [55]:
# Take sine of all values :)
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [56]:
# Take the cos, sin, and even tan
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

# Linear Algebra

In [57]:
a = np.ones((2, 3)) # (row, column)
print(a)
b = np.full((3,2), 2) # ((row, column), value)
print(b)
# In matrices you have to have the rows be equivalent to the column of the other matrix
np.matmul(a, b) # This is a matrix built in func, normal 'a *b' wouldn't work

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [58]:
# Finding the determinant of a matrix
c = np.identity(3)
np.linalg.det(c) # np is the name of the numpy imported, linalg == linear algebra, det == determinat

1.0

# Statistics in Numpy/Matrices

In [59]:
stats = np.array([[1,2,3], [4, 5,6 ]]) # 2 dimensional array
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
#This gets the min value of stats
np.min(stats, axis = 1) # this will give the minimum of the first and seconf row


array([1, 4])

In [69]:
#This gets maximum value of stats
np.max(stats, axis = 1) # The biggest values in the 2 rows

array([3, 6])

In [74]:
np.sum(stats)# This is going to sum all the elements in the array/matrix
np.sum(stats, axis = 0) # This will add up all the terms gong downwards

array([5, 7, 9])

# Reorganizing Arrays

In [82]:
# Changing the shape of an array
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print(before.shape)

#re-assigning the values of the array to a new variable
after = before.reshape((8, 1)) # The reshape method uses double brackets '((r, c))'
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [87]:
#  Vertically stacking Matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1, v2]) # This is me stacking an array on top of another one
np.vstack([v1, v2, v2, v2]) # This will even give me multiple copies of th earray
# vstack is the built in function use to run the stacking



array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [91]:
#Horizontal stacks
h1 = np.ones((2, 4))
h2 = np.zeros((2,2))

h1
h2
np.hstack((h1, h2)) #This is horizontally stacking

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#Miscellaneous

Load data from file

# Mulitidimensional Arrays(2d/3d)

In [62]:
from numpy import *

In [63]:
arr1= array([
    
                [1,2,3,6,2,9],
                [4,5,6,7,5,3] # This is a 2 dimensional array
])
print(arr1)
print(arr1.dtype) # This gives the data type of the array which is 'int'
print(arr1.ndim) # This gives the dimension of the array
print(arr1.shape) # This is the (r, c)
print(arr1.size) # This will give you the total size of the entire block

[[1 2 3 6 2 9]
 [4 5 6 7 5 3]]
int32
2
(2, 6)
12


In [64]:
arr2 = arr1.flatten() # This changes the array from 2d to 1d
print(arr2)
arr3 = arr2.reshape(3, 4) # This changes the 1d array to a 3d own, by providing the number of columns and rows needed
print(arr3)
arr3 = arr2.reshape(2, 2, 3)
print(arr3)

[1 2 3 6 2 9 4 5 6 7 5 3]
[[1 2 3 6]
 [2 9 4 5]
 [6 7 5 3]]
[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [65]:
arr5 = array([
    [1,2,3,4], # This is a 2d array
    [5,6,7,8]  
])
m = matrix(arr5) # Changing the array to matrix so we can perform operations on it
print(arr5)
print(m)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [66]:
m = matrix('1 2 3 6; 4 5 6 7')  # This shows you don't need to create a seperate arrays to save the values
print(m) 

m = matrix('1 2 3; 6 4 5; 1 6 7')  # The semicolon is to change the rows and columns of the matrix/array
print(m)

# Printing the diagonal elements of m
print(diagonal(m))

# Printing the minimum element of an array
print(m.min())

#Printig the maximum value of an array
print(m.max())


[[1 2 3 6]
 [4 5 6 7]]
[[1 2 3]
 [6 4 5]
 [1 6 7]]
[1 4 7]
1
7


In [67]:
# Multiplying two matrices
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('2 4 6; 1 3 5; 3 6 9')

m3 = m1 + m2 # The addition is working well
print(m3)

m3 = m1 * m2 # This multiplication is not done properly
print(m3)

[[ 3  6  9]
 [ 7  7 10]
 [ 4 12 16]]
[[ 13  28  43]
 [ 31  66 101]
 [ 29  64  99]]
